apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events-reader
  namespace: pacman 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: events-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default


# Then run oc create token -n ${NAMESPACE} ${SERVICE_ACCOUNT}

# Alternatively, create a kubeconfig using the token:

#$ oc -n ${NAMESPACE} sa create-kubeconfig ${SERVICE_ACCOUNT} > ${SERVICE_ACCOUNT}.kubeconfig
