- name: Kafka events
  hosts: localhost
  sources:
    - ansible.eda.kafka:
       topic: syslog-ng
       #host: ec2-3-26-98-214.ap-southeast-2.compute.amazonaws.com
       host: ip-172-31-19-180.ap-southeast-2.compute.internal 
       port: 9092
       group_id: 0
  rules:

    - name: Kafka msg1 
      condition: event.body is search('do we see this in kafka',ignorecase=true)
      action:
       run_job_template:
         name: my_collection_demo 

#    - name: Kafka msg2 
#      condition: event.body is search('do we see this in syslog',ignorecase=true)
#      action:
#       run_playbook:
#         name: say-what.yml
#         extra_vars:
#           say: 'say bar'
