- name: Listen for pod events
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1 
        kind: Event
        namespace: pacman
        host: "{{ k8s_host }}"
        api_key: "{{ k8s_token }}"
  rules:
    - name: Notify Pacman application faulted 
      condition: event.resource.message is search('deleted pod',ignorecase=true)
      actions:
        - run_job_template:
            name: my_collection_demo
            organization: Default
            job_args:
              extra_vars:
                message: EDA | faulted 
                sleep: 1

#        - run_job_template:
#            name: "[EDA] Alertmanager ITSM"
#            organization: Default
#            set_facts: true
#            job_args:
#              extra_vars:
#                alertStatus: "{{ event.payload.status }}"


    - name: EDA | Notify Pacman application recovered 
      condition:
        all:
          - facts.message is defined
          - facts.message is search('Created container',ignorecase=true)
      actions:
        - run_job_template:
            name: my_collection_demo
            #name: "[EDA] Alertmanager ITSM"
            organization: Default
            job_args:
              extra_vars:
                message: EDA | recovered 
                ticket_number: "{{ events.m.message }}"
