---
- name: Listen for events on a webhook
  hosts: all 

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  ## Define the conditions we are looking for

  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool"

  ## Define the action we should take should the condition be met

    - name: Alertmanager Action 
      condition: event.payload.status == "firing"
      action:
       run_job_template:
         name: my_collection_demo
         organization: Default
         job_args:
           extra_vars:
             message: from eda
             sleep: 1
